### ISSUE TITLE
Should be renamed to zinit-configs

### ISSUE THREAD

**Issue by unixorn** [zdharma/zinit-configs#22]
Should be renamed to Zinit-configs per the zplugin -> zinit renaming

**Comment by psprint** [comment]
Thanks for bringing this up. I've did the rename + also updated the configs.

**Comment by unixorn** [comment]
I'll go update https://github.com/unixorn/awesome-zsh-plugins

**Comment by psprint** [comment]
Great! Could you also do a substitution: `s:zplugin/z-a-:zinit-zsh/z-a-:`?

**Comment by unixorn** [comment]
Done as part of https://github.com/unixorn/awesome-zsh-plugins/pull/873

**Comment by psprint** [comment]
Cool!
